name: registro_panela
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  collection: ^1.19.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.1.0
  flutter_riverpod: ^2.6.1
  form_builder_validators: ^11.2.0
  freezed_annotation: ^3.1.0
  go_router: ^16.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

  fonts:
    - family: RobotoVariableItalic
      fonts:
        - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
          weight: 400
          style: normal


