// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARAW1wYu_l597XQbHTHj9sLRZ7p-ii-EQ',
    appId: '1:55019937253:web:4766c0975f1f0a13eb630c',
    messagingSenderId: '55019937253',
    projectId: 'registro-panela',
    authDomain: 'registro-panela.firebaseapp.com',
    storageBucket: 'registro-panela.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM7vPO0QyY2-sAmSuzIR_Mr94NB5CgyZ4',
    appId: '1:55019937253:android:507b13425535451eeb630c',
    messagingSenderId: '55019937253',
    projectId: 'registro-panela',
    storageBucket: 'registro-panela.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJS3l-nK4P38dDWss9_T4pL5wSkKFOeJU',
    appId: '1:55019937253:ios:3e73d28f1bd41b91eb630c',
    messagingSenderId: '55019937253',
    projectId: 'registro-panela',
    storageBucket: 'registro-panela.firebasestorage.app',
    iosBundleId: 'com.example.registroPanela',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJS3l-nK4P38dDWss9_T4pL5wSkKFOeJU',
    appId: '1:55019937253:ios:3e73d28f1bd41b91eb630c',
    messagingSenderId: '55019937253',
    projectId: 'registro-panela',
    storageBucket: 'registro-panela.firebasestorage.app',
    iosBundleId: 'com.example.registroPanela',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARAW1wYu_l597XQbHTHj9sLRZ7p-ii-EQ',
    appId: '1:55019937253:web:1a43edbb5efa6c6aeb630c',
    messagingSenderId: '55019937253',
    projectId: 'registro-panela',
    authDomain: 'registro-panela.firebaseapp.com',
    storageBucket: 'registro-panela.firebasestorage.app',
  );
}
